# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rae}
  s.version = "1.5.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["David A. Cuadrado", "Koldo Oteo"]
  s.date = %q{2010-08-21}
  s.default_executable = %q{rae}
  s.description = %q{library to access the rae.es}
  s.email = %q{krawek@gmail.com}
  s.executables = ["rae"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "bin/rae",
     "lib/rae.rb",
     "rae.gemspec"
  ]
  s.homepage = %q{http://github.com/dcu/rae}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{library to access the rae.es}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<mechanize>, [">= 1.0.0"])
    else
      s.add_dependency(%q<mechanize>, [">= 1.0.0"])
    end
  else
    s.add_dependency(%q<mechanize>, [">= 1.0.0"])
  end
end

